# Generated by Django 2.0.4 on 2018-05-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventclass',
            name='label',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='label',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
